Killer.create(first_name: "Harold", last_name: "Shipman", gender: "M", nickname: "Dr. Death", date_of_murders: "1974-1998", nationality: "British", bed_wetter: false, pyromania: false, animal_torturer: true, relationship_status: "married", occupation: "Physician, General Practition", legal_status: "Found guilty of 15 murders. Sentenced to life imprisonment and the judge recommended that he never be released on January 31, 2000.", article_url: "https://www.telegraph.co.uk/news/2018/04/26/did-harold-shipman-kill-250-patients/", alive: false)

Killer.create(first_name: "Ted", last_name: "Bundy", gender: "M", nickname: "The Riverman", date_of_murders: "1973-1978", nationality: "American", bed_wetter: true, pyromania: true, animal_torturer: true, relationship_status: "divorced", occupation: "Polical Campaigner", legal_status: "Executed by electrocution in Florida on January 24, 1989.", article_url: "https://www.nytimes.com/1989/01/25/us/bundy-is-put-to-death-in-florida-after-admitting-trail-of-killings.html", alive: false)

Killer.create(first_name: "Aileen", last_name: "Wuornos", gender: "F", nickname: "Damsel of Death", date_of_murders: "1989-1990", nationality: "American", bed_wetter: false, pyromania: false, animal_torturer: false, relationship_status: "divorced", occupation: "Prostitute", legal_status: "Executed by lethal injection in Florida on October 9, 2002.", article_url: "http://articles.latimes.com/1992-01-28/news/mn-1021_1_aileen-wuornos", alive: false)

Killer.create(first_name: "Belle", last_name: "Gunness", gender: "F", nickname: "The Black Widow", date_of_murders: "1800-1908", nationality: "American", bed_wetter: false, pyromania: true, animal_torturer: false, relationship_status: "single", occupation: "Insurance Fraud", legal_status: "On April 28, Gunness burned her home to the ground to stage her own death and skipped town. Her children died in the fire, but she was never tracked down and her death has never been confirmed.", article_url: "http://articles.latimes.com/1992-01-28/news/mn-1021_1_aileen-wuornos", alive: false)

Killer.create(first_name: "Nannie", last_name: "Doss", gender: "F", nickname: "The Giggling Grandma", date_of_murders: "1920-1954", nationality: "American", bed_wetter: false, pyromania: false, animal_torturer: false, relationship_status: "divorced", occupation: "Cotton Mill Worker", legal_status: "Pleaded guilty on May 17, 1955, and was sentenced to life imprisonment.", article_url: "https://www.tulsaworld.com/blogs/news/throwbacktulsa/throwback-tulsa-charming-friendly-nannie-doss-poisoned-four-husbands/article_c43b83ff-f12e-5952-a64b-21a1c0fbdcd4.html", alive: false)

Killer.create(first_name: "John", last_name: "Gacy", gender: "M", nickname: "The Killer Clown", date_of_murders: "1972-1978", nationality: "American", bed_wetter: false, pyromania: true, animal_torturer: true, relationship_status: "divorced", occupation: "Children's Party Clown", legal_status: "Executed by lethal injection in Illinois on May 10, 1994", article_url: "http://www.chicagotribune.com/news/nationworld/politics/chi-chicagodays-gacy-story-story.html", alive: false)

Killer.create(first_name: "Edward", last_name: "Gein", gender: "M", nickname: "The Butcher of Plainfield", date_of_murders: "1954-1957", nationality: "American", bed_wetter: true, pyromania: true, animal_torturer: false, relationship_status: "single", occupation: "Farmer", legal_status: "Sentenced to life imprisonment, 1968. Found not guilty by reason of insanity and acquitted. Transferred to mental hospital.", article_url: "http://time.com/3879490/ed-gein-portrait-of-americas-original-psycho-killer/", alive: false)

Killer.create(first_name: "Jeffrey", last_name: "Dahmer", gender: "M", nickname: "TThe Milwaukee Cannibal", date_of_murders: "1978-1991", nationality: "American", bed_wetter: true, pyromania: false, animal_torturer: true, relationship_status: "single", occupation: "Unemployed", legal_status: "Pleaded not guilty by reason of insanity. Sentenced to 15 life terms, totaling 957 years in prison, in Wisconsin on February 15, 1992. Sentenced to life in prison in Ohio in May 1992.", article_url: "http://www.nydailynews.com/news/crime/jeffrey-dahmer-milwaukee-cannibal-caught-1991-article-1.2298878", alive: false)
